### ISSUE TITLE
Work on other repos in the rust-lang org

### ISSUE THREAD

**Issue by nick29581** [nick29581/highfive#23]
cc @huonw

I did the first part of this - making choosing a reviewer generic over the repo.

Still todo:

* make rust-highfive an admin or owner or whatever on the repos we want to cover
* add the GitHub hooks to these repos
* change the link to contributing.md in the welcome message (maybe, perhaps the rust one is fine for all repos)
* create `repo.json` files for each repo with the list of people to use as reviewers
* test that it actually works!

**Comment by huonw** [comment]
I created a @rust-lang/bots team that has write access to essentially all the relevant rust-lang repos, and added rust-highfive to it.

Do you know if there's a way to mass-add github hooks to repos? I don't feel like going through and adding them to 28 different repos. :smile: (Also, what sort of hooks? Just the same as for rust-lang/rust?)

**Comment by nick29581** [comment]
Yeah, I'm sure you can use the API to do that, probably the easiest thing would be for me to write the script then temporarily give rust-highfive admin powers to run the script. And yes, just the same as the rust one. I would like to test with just one repo first though to minimise the damage in case something does go wrong. So let's pick a low traffic repo on Monday and we'll manually do that, and if it goes smoothly then we script the other hooks (and come up with the reviewers files).

**Comment by nick29581** [comment]
Which repos should we work on:

rust-www
rust-playpen
libuv
gyp
llvm
compiler-rt
cargo
rust-by-example
hoedown
jemalloc
rust-guidelines
crates.io
semver
fourcc
uuid
glob
blog.rust-lang.org
num
url
rust-packaging
rlibc
crates.io-index
time
rust-installer
rust-buildbot
rustc-serialize

**Comment by huonw** [comment]
The repos rust-highfive has access to atm are (I tried to omit pointless repos, obviously it can be extended):

rust-lang / blog.rust-lang.org
rust-lang / cargo
rust-lang / fourcc
rust-lang / getopts
rust-lang / glob
rust-lang / hexfloat
rust-lang / hoedown
rust-lang / jemalloc
rust-lang / llvm
rust-lang / log
rust-lang / num
rust-lang / regex
rust-lang / rfcs
rust-lang / rlibc
rust-lang / rust
rust-lang / rust-buildbot
rust-lang / rust-by-example
rust-lang / rust-guidelines
rust-lang / rust-installer
rust-lang / rust-packaging
rust-lang / rust-playpen
rust-lang / rust-www
rust-lang / rustc-serialize
rust-lang / semver
rust-lang / term
rust-lang / time
rust-lang / url
rust-lang / uuid

**Comment by nick29581** [comment]
I think this is all done now. I haven't changed the welcome message, it still points to the rust one, but I think that is OK.
