### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by nick29581** [nick29581/highfive#40]
If I run the tests following the instructions in README.md, I get errors. First I get an indentation error at line 76 in test_cr.py. I tried fixing that by removing the initial spaces on that line. Then I get the error:

```
  File "/home/ncameron/highfive/test_cr.py", line 71, in <module>
    df = open('diff.diff')
IOError: [Errno 2] No such file or directory: 'diff.diff'
```

I don't see diff.diff anywhere, so I'm not sure how to fix this.

cc @flaper87

**Comment by FlaPer87** [comment]
@nick29581 you need to subclass [`highfive.tests.base.BaseClass`](https://github.com/nick29581/highfive/blob/master/highfive/tests/base.py#L6) and use [`self._load_fake`](https://github.com/nick29581/highfive/blob/master/highfive/tests/base.py#L8) to load a fake file.

The `test_cr.py` file should go into `highfilve/tests` directory and the `diff.diff` file in the `highfive/tests/fakes` directory.

**Comment by nick29581** [comment]
False alarm, I had an old python file in the top directory called `test_cr.py` and that was being treated like a test when it wasn't. I deleted that and now the tests run
