### ISSUE TITLE
Check boxes which refererence closed issues

### ISSUE THREAD

**Issue by mdinger** [nick29581/highfive#44]
https://github.com/rust-lang/rust/issues/20761 is populated with checkboxes like below:
- [ ] Is this bug closed https://github.com/nick29581/highfive/issues/44:

Highfive could check the boxes anytime the issues referenced are closed.

**Comment by mdinger** [comment]
Bors could too. I can move this to bors if you think that's a better place for it.

**Comment by nick29581** [comment]
Probably better for bors to do it, since that bot is already responsible for closing issues

**Comment by mdinger** [comment]
Moved to https://github.com/barosl/homu/issues/52
